plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '8.10.2'
	id 'org.owasp.dependencycheck' version '13.0.0'
	id 'checkstyle'
}

group = 'com.team'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	java {
		googleJavaFormat('1.36.0')

		removeUnusedImports()
		forbidWildcardImports()

		trimTrailingWhitespace()
		endWithNewline()
	}
}

checkstyle {
	toolVersion = '14.1.0'
}

def nvdApiKey = System.getenv('NVD_API_KEY')

dependencyCheck {
	if (nvdApiKey?.trim()) {
		nvd {
			apiKey = nvdApiKey
		}
	}
}
