name: CI backend

on:
  push:
    branches:
      - "feat/**"
      - "chore/**"

jobs:
  feature_ci:
    name: Feature validation
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check source
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Lint
        run: ./gradlew check -x test -x spotlessCheck

      - name: Formatter Check
        run: ./gradlew spotlessCheck

      - name: Dependency Vulnerability Check
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }} #보안 취약점을 검사하는데 해당 부분의 api 호출이 필요함.
        run: ./gradlew dependencyCheckAnalyze
        
      - name: Build
        run: ./gradlew  bootJar -x test #clean삭제 앞단에서 컴파일된 파일 사용.
