name: CI backend

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
      - "chore/**"

jobs:
  feature_ci:
    name: Feature validation
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check source
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Lint
        run: ./gradlew  spotlessCheck
        #0919 : lint를 돌려본 결과 CI에서 기존에 올라간 코드에 import -*되어 있는 것 때문에 실패함.(이건 직접 수정이 필요함)
        #build.gradle파일에  spotless 설정후 터미널에서 ./gradlew spotlessApply 해당 명령어 실행하면 자동으로 삭제됨. 이후 github에 올리는 건 성공하게됨.


      - name: Formatter Check
        run: ./gradlew spotlessCheck

      - name: Dependency Vulnerability Check
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }} #보안 취약점을 검사하는데 해당 부분의 api 호출이 필요함.
        run: ./gradlew dependencyCheckAnalyze
        
      - name: Build
        run: ./gradlew  bootJar -x test #clean삭제 앞단에서 컴파일된 파일 사용.
